### ISSUE TITLE
Enable elliptic-curve cryptography (ECC) support in Erlang packages

### ISSUE THREAD

**Issue by zeqfreed** [essentialkaos/kaos-repo#179]
Hello. I'm using Erlang OTP/20 and receive the following warning from hackney_ssl:
```
03:18:41.979 [warn] hackney_ssl: ECC not enabled
```

A quick investigation showed that Erlang's crypto package does not support ECC although system's openssl version does:
```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.1  (abort with ^G)
1> lists:member(ecdh, proplists:get_value(public_keys, crypto:supports())).
false
```

```
# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

openssl list-public-key-algorithms | grep EC
Name: OpenSSL EC algorithm
        PEM string: EC
```

As it turns out, elliptic-curve cryptography is explicitly disabled during Erlang build process via compilation flag `-DOPENSSL_NO_EC=1` in https://github.com/essentialkaos/kaos-repo/blob/master/erlang-R20/erlangR20.spec#L779. This was probably done previously to support an older version of openssl.

I'd like to use ECC public keys in my application and ask you kindly to modify build scripts to enable ECC support in Erlang's crypto package.

**Comment by andyone** [comment]
Hi! Looks like it legacy from old times when we used OpenSSL 0.9.8 which doesn't support EC. I will check build without this rule, and if all be ok, I will try to rebuild all versions of erlang without this rule.

**Comment by andyone** [comment]
@zeqfreed I have rebuilt Erlang 17, 18, 19 and 20 with statically linked LibreSSL (`2.6.4`) and enabled ECC support. Could you please check any of this versions (currently available in `kaos-testing` repository)?

**Comment by zeqfreed** [comment]
@andyone I've reinstalled `erlang20` from `kaos-testing` repo and now `crypto` module supports `ecdh` public keys as desired:
```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.1  (abort with ^G)
1> lists:member(ecdh, proplists:get_value(public_keys, crypto:supports())).
true
```

Also there are no more warnings from `hackney_ssl`, and everything appears to be working smoothly. Thank you for the quick response!

**Comment by andyone** [comment]
Glad to hear that. I will add this packages to release repository as part of release #171
