### ISSUE TITLE
python34-tornado and saltstack issue

### ISSUE THREAD

**Issue by dexoid** [essentialkaos/kaos-repo#188]
Hello.
After updating the packages, a python34-tornado version 5.x was installed. But saltstack based on python3 does not work with this version of python34-tornado.

**Comment by andyone** [comment]
Hi! Thank you for reporting about that. I will fix it as soon as possible.

**Comment by andyone** [comment]
@dexoid I have been rebuilt and added `salt-2018.3.2-1` to `testing` repository with the fix (`python34-tornado` limited to < 5.0). Could you please check this version?

**Comment by dexoid** [comment]
with the test repository everything is fine

**Comment by andyone** [comment]
Glad to hear that. `salt-2018.3.2-1` has been added to release directory.
