### ISSUE TITLE
MMGeoIP: add ASN to package

### ISSUE THREAD

**Issue by gongled** [essentialkaos/kaos-repo#235]
Hi, @andyone.

First of all, I am appreciate your contribution to the opensource community and providing RPM packages for CentOS/RHEL distributions.

I am looking for your opinion to improve the MaxMind GeoIP base RPM package. I offer you include ASN (autonomous systems information) in CSV format to the `MMGeoIP` and `MMGeoIP-IPV6` packages.

What do you think about this proposal?

I am also a bit confused with a [MaxMind blog article](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/). According to the text, it is mandatory to be a registered user to download databases. I do not know how to use the license key they assign to the user with RPMBuilder in the context of building RPM packages.

Do you have any ideas on how to bypass it?

**Comment by andyone** [comment]
Hi! Thanks for your kind words. 😊

> I offer you include ASN (autonomous systems information) in CSV format to the MMGeoIP and MMGeoIP-IPV6 packages.

We can add them as sub-packages to keeping the size of packages within reasonable limits.

> I do not know how to use the license key they assign to the user with RPMBuilder in the context of building RPM packages.

If I understand their post right, they provide direct links, but we should add the license key as a part of the URL. So we can use these links and add the license key macro to sources URLs, and define it on build stage through `--define` option. In this case, everyone could build these packages using their own license key.

**Comment by gongled** [comment]
> So we can use these links and add the license key macro to sources URLs, and define it on build stage through `--define` option.

That's sounds great! Is there any help needed with this change?

**Comment by andyone** [comment]
Thanks, no help needed. I have done these changes (e390e07c0bbba3e11e6b769ec1f468bff66f96dd), but unfortunately, MaxMind URLs don't contain filenames and we can't use macros for the license key. So I created the script for downloading MaxMind data.

Also, since this version every type of data packed to separate package (_IPv4/IPv6/ASN-IPv4/ASN-IPv6_).
