### ISSUE TITLE
Unable to build heka 0.10.0

### ISSUE THREAD

**Issue by gongled** [essentialkaos/kaos-repo#90]
@andyone, I've tried to prepare PR for `heka` 0.10.0 and found that file `heka-man.tar.gz` is missing. What should we do? Probably, you should add this gz-archive to the repository or I can skip it on during preparing new version.

**Comment by andyone** [comment]
I think that the use prerendered man docs was wrong decision. We must generate man docs but this require `python-sphinx` package > 1.0. I will try to write spec file for this package tonight.

**Comment by gongled** [comment]
Sounds good for me.

**Comment by gongled** [comment]
We waited so long that the Mozilla's project has [already stopped developing](https://mail.mozilla.org/pipermail/heka/2016-May/001059.html). I think we should close this issue and never ever built it RPM package for this.

**Comment by andyone** [comment]
:laughing: I so love Mozilla's projects...
