### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by simukti** [essentialkaos/kaos-repo#91]
Hello, @andyone , Go 1.6.3 and vips 8.3.1 is out now, it would be awesome if you update the rpm specs. 

Thank you.

**Comment by andyone** [comment]
Hi @simukti sorry for delay. Latest versions of golang and vips was added to `testing` repository and can be installed through `yum --enablerepo=kaos-testing install` command.

Packages will be available in `release` repository after tests for production ready state in PR #85.
